GET http://localhost:3098


###

POST http://localhost:3098/api/v1/auth/signup
Content-Type: application/json

{
    "email": "franco@gmail.com",
    "password": "franco1234",
    "username": "fr4nc0_2098"
}

###

POST http://localhost:3098/api/v1/auth/loggin
Content-Type: application/json

{
    "email": "franco@gmail.com",
    "password": "franco1234"
}

###

GET http://localhost:3098/api/v1/products
Authorization: Bearer <token>

###
GET http://localhost:3098/api/v1/products/624edfdabb4bb65f76bcafe9
Authorization: Bearer <token>

###

GET http://localhost:3098/api/v1/non-exist-route